@api = http://localhost:3020/api/v1/libros
GET {{api}}
###

GET http://localhost:3020/api/v1/peliculas
###
GET http://localhost:3020/api/v1/peliculas/1
###
POST http://localhost:3020/api/v1/peliculas
Content-Type: application/json

{
    "id": 1,
    "title": "Inception",
    "director": "Christopher Nolan",
    "year": 2010,
    "genre": "Science Fiction"
}
###
PUT http://localhost:3020/api/v1/peliculas/1
Content-Type: application/json

{
    "title": "Inception (Updated)"
}


###
DELETE http://localhost:3020/api/v1/peliculas/1
###